import { Ingredient } from "@/types/Ingredients";

export const DB_ingredients: Ingredient[] = [
  {
    name: "Water",
    CASNumber: "7732-18-5",
    localName: "Water",
    formula: "H2O",
    tradeName: "Water",
    isBiomass: false,
    isSolid: false,
    molecularWeight: 18.015, //g/mol
    boilingPoint: 100,
    boilingPointUnit: "C",
    criticalTemp: 374.19,
    criticalTempUnit: "C",
    criticalPressure: 221.2,
    criticalPressureUnit: "bar",
    compressabilityFactor: 0.235,
    enthalpyOfFormationUnit: "J/mol",
    enthalpyOfFormation: -285.82,
    freezingTemp: 0,
    freezingTempUnit: "C",
    henrysConstant: 0, //atm m3 / mon
    particleSize: 0, //micron
    volumetricConstant: 1,
    liquidDensityUnit: "g/L",
    liquidDensityCoefA: 1103.38,
    liquidDensityCoefB: -0.3645,
    heatCapacityUnit: "J/mol·K",
    liquidHeatCapacityCoefA: 276.37,
    liquidHeatCapacityCoefB: -209.01,
    liquidHeatCapacityCoefC: 81.25,
    liquidHeatCapacityCoefD: -1411.6,
    liquidHeatCapacityCoefE: 937010000,
    gasHeatCapacityCoefA: 32.24,
    gasHeatCapacityCoefB: 0.1924,
    gasHeatCapacityCoefC: 0.1055,
    gasHeatCapacityCoefD: -0.3596,
    gasHeatCapacityCoefE: 0,
    vaporPressureCeofA: 8.06,
    vaporPressureCeofB: 1725.328,
    vaporPressureCeofC: -40.0199,
    heatOfVaporizationUnit: "J/mol",
    heatOfVaporizationCoefA: 56715.3554,
    heatOfVaporizationCoefB: 0.38,
    purchasePrice: 0,
    purchasePriceUnit: "kg",
    sellingPrice: 0,
    sellingPriceUnit: "kg",
  },
  {
    name: "Oxygen",
    CASNumber: "7782-44-7",
    localName: "O2",
    formula: "O2",
    tradeName: "Oxygen",
    isBiomass: false,
    isSolid: false,
    molecularWeight: 31.999, //g/mol
    boilingPoint: -182.84,
    boilingPointUnit: "C",
    criticalTemp: -118.39,
    criticalTempUnit: "C",
    criticalPressure: 51.81,
    criticalPressureUnit: "bar",
    compressabilityFactor: 0.288,
    enthalpyOfFormationUnit: "J/mol",
    enthalpyOfFormation: 0,
    freezingTemp: -218.79,
    freezingTempUnit: "C",
    henrysConstant: 0, //atm m3 / mon
    particleSize: 0, //micron
    volumetricConstant: 1,
    liquidDensityUnit: "g/L",
    liquidDensityCoefA: 1620.47,
    liquidDensityCoefB: -5.2931,
    heatCapacityUnit: "J/mol·K",
    liquidHeatCapacityCoefA: 97,
    liquidHeatCapacityCoefB: 0,
    liquidHeatCapacityCoefC: 0,
    liquidHeatCapacityCoefD: 0,
    liquidHeatCapacityCoefE: 0,
    gasHeatCapacityCoefA: 28.11,
    gasHeatCapacityCoefB: -0.0003,
    gasHeatCapacityCoefC: 0.1746,
    gasHeatCapacityCoefD: -0.065,
    gasHeatCapacityCoefE: 0,
    vaporPressureCeofA: 6.6914,
    vaporPressureCeofB: 319.013,
    vaporPressureCeofC: -6.5,
    heatOfVaporizationUnit: "J/mol",
    heatOfVaporizationCoefA: 9557.0781,
    heatOfVaporizationCoefB: 0.3638,
    purchasePrice: 0,
    purchasePriceUnit: "kg",
    sellingPrice: 0,
    sellingPriceUnit: "kg",
  },
  {
    name: "Nitrogen",
    CASNumber: "7727-37-0",
    localName: "Nitrogen",
    formula: "N2",
    tradeName: "Nitrogen",
    isBiomass: false,
    isSolid: false,
    molecularWeight: 28.013, //g/mol
    boilingPoint: -195.75,
    boilingPointUnit: "C",
    criticalTemp: -146.9,
    criticalTempUnit: "C",
    criticalPressure: 34.65,
    criticalPressureUnit: "bar",
    compressabilityFactor: 0.29,
    enthalpyOfFormationUnit: "J/mol",
    enthalpyOfFormation: 0,
    freezingTemp: -210,
    freezingTempUnit: "C",
    henrysConstant: 0, //atm m3 / mon
    particleSize: 0, //micron
    volumetricConstant: 1,
    liquidDensityUnit: "g/L",
    liquidDensityCoefA: 1301.19,
    liquidDensityCoefB: -6.1226,
    heatCapacityUnit: "J/mol·K",
    liquidHeatCapacityCoefA: 88,
    liquidHeatCapacityCoefB: 0,
    liquidHeatCapacityCoefC: 0,
    liquidHeatCapacityCoefD: 0,
    liquidHeatCapacityCoefE: 0,
    gasHeatCapacityCoefA: 31.5,
    gasHeatCapacityCoefB: -1.357,
    gasHeatCapacityCoefC: 0.268,
    gasHeatCapacityCoefD: -1.168,
    gasHeatCapacityCoefE: 0,
    vaporPressureCeofA: 6.4945,
    vaporPressureCeofB: 255.68,
    vaporPressureCeofC: -6.65,
    heatOfVaporizationUnit: "J/mol",
    heatOfVaporizationCoefA: 7900.9418,
    heatOfVaporizationCoefB: 0.3584,
    purchasePrice: 0,
    purchasePriceUnit: "kg",
    sellingPrice: 0,
    sellingPriceUnit: "kg",
  },
  {
    name: "Sodium Hydroxide",
    CASNumber: "1310-73-2",
    localName: "Sodium Hydroxide",
    formula: "NaOH",
    tradeName: "Sodium Hydroxide",
    isBiomass: false,
    isSolid: false,
    molecularWeight: 39.997, //g/mol
    boilingPoint: 1578,
    boilingPointUnit: "C", // C, K, F, R
    criticalTemp: 2546.85,
    criticalTempUnit: "C",
    criticalPressure: 250,
    criticalPressureUnit: "bar",
    compressabilityFactor: 0.213,
    enthalpyOfFormationUnit: "J/mol",
    enthalpyOfFormation: -425930,
    freezingTemp: 322.85,
    freezingTempUnit: "C",
    henrysConstant: 0, //atm m3 / mon
    particleSize: 0, //micron
    volumetricConstant: 1,
    liquidDensityUnit: "g/L",
    liquidDensityCoefA: 2043.02,
    liquidDensityCoefB: -0.4349,
    heatCapacityUnit: "J/mol·K",
    liquidHeatCapacityCoefA: 87.1778,
    liquidHeatCapacityCoefB: 0,
    liquidHeatCapacityCoefC: 0,
    liquidHeatCapacityCoefD: 0,
    liquidHeatCapacityCoefE: 0,
    gasHeatCapacityCoefA: 43.5656,
    gasHeatCapacityCoefB: 1.7649,
    gasHeatCapacityCoefC: -0.0756,
    gasHeatCapacityCoefD: 0.1092,
    gasHeatCapacityCoefE: 0,
    vaporPressureCeofA: 5.753,
    vaporPressureCeofB: 5309.6304,
    vaporPressureCeofC: -4.406,
    heatOfVaporizationUnit: "J/mol",
    heatOfVaporizationCoefA: 441172.8351,
    heatOfVaporizationCoefB: 0.4616,
    purchasePrice: 5.0,
    purchasePriceUnit: "kg",
    sellingPrice: 0,
    sellingPriceUnit: "kg",
  },
];
